Update pillar.example to good-citizen defaults
saltstack-formulas/letsencrypt-formula pull request #63
Opened 2019-02-03 13:00 UTC by Artanicus

Specifying `renew-by-default` in the config, regardless of True / False enables the flag. This causes certbot to force-renew on every timer run and means you will hit the rate-limit fairly quickly. A safer default is `keep-until-expiring` where the renew will only be done when it's actually advisable.

`expand` allows an expanded domain list to renew correctly without forking a new domainset. This is something that most users will want.

2019-02-03 13:01 UTC, Artanicus commented
This will fix #58 and mitigate #57

2019-02-03 15:16 UTC, javierbertoli commented
@Artanicus , changing these values in `pillar.example` won't mitigate the issues you mention, as `pillar.example` is just that, an example.

 Adding these values to `defaults.yaml` will help (and I'd say adding them there would be a good thing), but #57 won't be fixed, that will require an extra PR.

Mind you add these values in `defaults.yaml` too, *keeping also* the old values in `pillar.example`?

2019-02-04 10:17 UTC, aanriot requested changes
I agree with @javierbertoli . Thanks for you work @Artanicus .

2019-02-04 15:44 UTC, aboe76 reviewed
I agree with @javierbertoli

2019-03-19 09:28 UTC, alxwr requested changes
I agree with @javierbertoli . Thanks for you work @Artanicus .

2020-07-23 19:19 UTC, javierbertoli commented
As this PR got stale, I updated and merged it on #73.

2020-07-23 19:19 UTC, closed without merging